// store data in js file 
products_1 =[
    {
    id: 1,
    name:"FOGG Spray",
    title: "Fogg Royal Perfume Spray for Men - 120 ml, Mixed",
    price: "840,00 EGP",
    discount: "Sale price 1770,00 EGP",
    imageURL: "images/foog1.jpg",
    qty: 1,
    },
    {
    id: 2,
    name:"Bleu de CHANEL",
    title: "Fogg Royal Perfume Spray for Men - 120 ml, Mixed",
    price: "950,00 EGP",
    discount: "Sale price 1270,00 EGP",
    imageURL: "images/foog3.jpg",
    qty: 1,
    },
    {
    id: 3,
    name:"Sauvage Dior",
    title: "Fogg Royal Perfume Spray for Men - 120 ml, Mixed",
    price: "360,00 EGP",
    discount: "Sale price 1150,00 EGP",
    imageURL: "images/foog2.jpg",
    qty: 1,
    },
    {
    id: 4,
    name:"Sauvage Dior",
    title: "Fogg Royal Perfume Spray for Men - 120 ml, Mixed",
    price: "360,00 EGP",
    discount: "Sale price 1150,00 EGP",
    imageURL: "images/foog3.jpg",
    qty: 1,
    },
    {
    id: 5,
    name:"Sauvage Dior",
    title: "Fogg Royal Perfume Spray for Men - 120 ml, Mixed",
    price: "360,00 EGP",
    discount: "Sale price 1150,00 EGP",
    imageURL: "images/foog2.jpg",
    qty: 1,
    },
    {
    id: 6,
    name:"Sauvage Dior",
    title: "Fogg Royal Perfume Spray for Men - 120 ml, Mixed",
    price: "360,00 EGP",
    discount: "Sale price 1150,00 EGP",
    imageURL: "images/foog1.jpg",
    qty: 1,
    }
];
// Define data
let products_2 = [
    {
        id: 7,
        name:"Man look",
        discount: "20% discount",
        offer: "Limited time offer",
        title: "Man look Spray for Men - 120 ml, Mixed",
        price: "800,00 EGP",
        Sale: "Sale price 1110,00 EGP",
        imageURL: "images/1.jpg",
        qty: 1,
    },
    {
        id: 8,
        name:"lona",
        discount: "30% discount",
        offer: "Limited time offer",
        title: "lona Perfume Spray for Men - 120 ml, Mixed",
        price: "900,00 EGP",
        Sale: "Sale price 2270,00 EGP",
        imageURL: "images/2.jpg",
        qty: 1,
    },
    {
        id: 9,
        name:"ck",
        discount: "25% discount",
        offer: "Limited time offer",
        title: "ck Perfume Spray for Men - 120 ml, Mixed",
        price: "840,00 EGP",
        Sale: "Sale price 1170,00 EGP",
        imageURL: "images/3.jpg",
        qty: 1,
    },
    {
        id: 10,
        name:"Man look",
        discount: "15% discount",
        offer: "Limited time offer",
        title: "FOGG Royal Perfume Spray for Men - 120 ml, Mixed",
        price: "840,00 EGP",
        Sale: "Sale price 8570,00 EGP",
        imageURL: "images/4.jpg",
        qty: 1,
    },
    {
        id: 11,
        name:"sauvage",
        discount: "10% discount",
        offer: "Limited time offer",
        title: "sauvage Perfume Spray for Men - 120 ml, Mixed",
        price: "1000,00 EGP",
        Sale: "Sale price 1980,00 EGP",
        imageURL: "images/5.jpg",
        qty: 1,
    },
    {
        id: 12,
        name:"lion look",
        discount: "45% discount",
        offer: "Limited time offer",
        title: "lion look Perfume Spray for Men - 120 ml, Mixed",
        price: "740,00 EGP",
        Sale: "Sale price 2000,00 EGP",
        imageURL: "images/6.jpg",
        qty: 1,
    },
    {
        id: 13,
        name:"Grit",
        discount: "55% discount",
        offer: "Limited time offer",
        title: "Grit Royal Perfume Spray for Men - 120 ml, Mixed",
        price: "140,00 EGP",
        Sale: "Sale price 1170,00 EGP",
        imageURL: "images/7.jpg",
        qty: 1,
    },
    {
        id: 14,
        name:"Royal",
        discount: "70% discount",
        offer: "Limited time offer",
        title: "Royal Perfume Spray for Men - 120 ml, Mixed",
        price: "100,00 EGP",
        Sale: "Sale price 1140,00 EGP",
        imageURL: "images/8.jpg",
        qty: 1,
    },
    {
        id: 15,
        name:"shrot",
        discount: "90% discount",
        offer: "Limited time offer",
        title: "shroty Royal Perfume Spray for Men - 120 ml, Mixed",
        price: "50,00 EGP",
        Sale: "Sale price 1170,00 EGP",
        imageURL: "images/9.jpg",
        qty: 1,
    },
];
// store data in js file 
products_3 =[
    {
        id: 16,
        name:"shroty",
        imageURL: "images/foog2.jpg",
        price: "800,00 EGP",
        Sale: "1250,00 EGP",
        qty: 1,
    },
    {
        id: 17,
        name:"Rex",
        imageURL: "images/c2.jpg",
        price: "780,00 EGP",
        Sale: "1630,00 EGP",
        qty: 1,
    },
    {
        id: 18,
        name:"yellow",
        imageURL: "images/c3.jpg",
        price: "880,00 EGP",
        Sale: "1860,00 EGP",
        qty: 1,
    },
    {
        id: 19,
        name:"black",
        imageURL: "images/c4.jpg",
        price: "900,00 EGP",
        Sale: "2900,00 EGP",
        qty: 1,
    },
    {
        id: 20,
        name:"black",
        imageURL: "images/foog1.jpg",
        price: "900,00 EGP",
        Sale: "2900,00 EGP",
        qty: 1,
    }
]
localStorage.setItem("products_1", JSON.stringify(products_1 ));
localStorage.setItem("products_2", JSON.stringify(products_2 ));
localStorage.setItem("products_3", JSON.stringify(products_3 ));